plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.5'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'bookSystem'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
    // 1. 스프링 웹 기능 (Controller, RequestBody, HttpServletRequest 등)
    implementation 'org.springframework.boot:spring-boot-starter-web'

    // 2. DB와 연결해주는 JPA 기능 (@Entity, JpaRepository 등)
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // 3. 롬복 기능 (@Getter, @Setter 자동 생성)
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // 4. MySQL 연결 드라이버 (이미 추가되어 있을 수도 있습니다)
    runtimeOnly 'com.mysql:mysql-connector-j'

    // 기본적으로 있는 테스트 설정 (그대로 두시면 됩니다)
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
	useJUnitPlatform()
}
