spring.application.name=bookSystemDB

# DB ?? ??
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/bookSystemDB?serverTimezone=Asia/Seoul
spring.datasource.username=bookSystem
spring.datasource.password=book

# JPA ??
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# 파일 업로드 용량 제한 (필요시 조절)
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# 파일이 저장될 실제 컴퓨터 물리 경로(절대 경로)
file.upload-dir=C:/CE/team05_bookSystem/-team05_bookSystem-Test/src/main/resources/static/images/
